---
fullname: Stable sort algorithms in Coq
shortname: stablesort
organization: pi8027
action: true
dune: false

synopsis: >-
  Stable sort algorithms and their stability proofs in Coq

description: |-
  This library provides two kinds of optimized mergesort functions implemented
  in Coq.
  The first kind is non-tail-recursive mergesort functions, which allows us to
  compute the first k smallest elements of a list of length n in the optimal
  O(n + k log k) time complexity of the partial and incremental sorting
  problems, in the call-by-need evaluation. However, the non-tail-recursive
  merge function linearly consumes the call stack and triggers a stack overflow
  in the call-by-value evaluation.
  The second kind is tail-recursive mergesort functions and thus solves the
  above issue in the call-by-value evaluation. However, it does not allow us to
  compute the output incrementally in the optimal O(n + k log k) time regardless
  the evaluation strategy.

  To prove correctness (including stability) of these best mergesort functions
  depending on the situation, this library also provides a generic way to prove
  these properties. The stability lemmas provided in this library are overloaded
  using a canonical structure (`StableSort.function`), and stable sort functions
  are characterized in this interface by the parametricity axiom and binary
  trees representing the divide-and-conquer structure of sort. One may prove the
  stability of a new sorting function by using the parametricity translation
  (Paramcoq) and providing a lemma corresponding to the binary tree
  construction.

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: sakaguchi@coins.tsukuba.ac.jp

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.15~") | (= "dev")}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '1.12.0-coq-8.10'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.11'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.12'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.13'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.14'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.12.0") | (= "dev")}'
  description: |-
    [MathComp](https://math-comp.github.io) 1.12.0 or later
- opam:
    name: coq-paramcoq
    version: '{(>= "1.1.2") | (= "dev")}'
  description: |-
    [Paramcoq](https://github.com/coq-community/paramcoq) 1.1.2 or later

namespace: stablesort

documentation: |-
  ## Credits
  The mergesort functions and the stability proofs provided in this library are
  mostly based on ones in the `path` library of Mathematical Components.
---
